package com.nancy.mapper;

import com.nancy.entity.Book;
import org.apache.ibatis.annotations.Param;
import tk.mybatis.mapper.common.Mapper;

import java.util.List;

public interface BookMapper extends Mapper<Book> {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table book
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table book
//     *
//     * @mbggenerated
//     */
//    int insert(Book record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table book
//     *
//     * @mbggenerated
//     */
//    int insertSelective(Book record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table book
//     *
//     * @mbggenerated
//     */
//    Book selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table book
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKeySelective(Book record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table book
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(Book record);

    List<Book> selectAllBook();
    List<Book> searchName(@Param("name") String  name);

}